<?php 
function get_woo_builder_get_placeholder_html( $behavior, $custom_url, $name ) {
    if ( $behavior === 'hide_placeholder' ) {
        return '';
    }

    if ( $behavior === 'custom_image' && ! empty( $custom_url ) ) {
        // Render the custom image
        return '<img src="' . esc_url( $custom_url ) . '" alt="' . esc_attr__( 'Placeholder', 'woo-builder' ) . '" class="category-placeholder custom-placeholder" />';
    }

    $icon_svg = '<svg viewBox="0 0 24 24" fill="currentColor" width="24" height="24"><path d="M0 0h24v24H0z" fill="none"/><path d="M4 6h16v12H4zm2 2v8h12V8z"/></svg>'; 
    
    return '<div class="category-placeholder default-icon">' . $icon_svg . '<span>' . esc_html__( 'No Image Available', 'woo-builder' ) . '</span></div>';
}


/**
 * Destroys all transients generated by the WooCommerce Categories block.
 * This should be attached to hooks that signify a change in category data.
 */
function wbb_clear_category_transients() {
    $transient_base = 'wbb_woo_categories_';

    delete_transient( 'wbb_woo_categories_total_count' ); 
    $cache_keys_to_clear = [
        'wbb_woo_categories_base_query_hash1', 
    ];
    foreach ( $cache_keys_to_clear as $key ) {
        delete_transient( $key );
    }
    delete_transient( 'wbb_woo_categories_total_count' ); 
}

// Hooks when WooCommerce category data changes:
add_action( 'edited_product_cat', 'wbb_clear_category_transients' ); // Category updated
add_action( 'created_product_cat', 'wbb_clear_category_transients' ); // Category created
add_action( 'delete_product_cat', 'wbb_clear_category_transients' ); // Category deleted
add_action( 'woocommerce_after_product_object_save', 'wbb_clear_category_transients' ); // Product saved (count may change)